language: node_js
node_js:
- '13'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: reactdesafio
  api_key:
    secure: Qab/10pwpbFmYhPhYyBYY+JOg+uxluwz019AgCazKSZMhfKCGk2Vq481uYmRf2yK0/amYDXLPc01ywiVq2wjfXTQw99z/t/gtIVKbr1QQJglusV7KIocNABLa25yigsQUMigvJB1KGcmOgk1Gj4BHZePlCDoab/xHFZLGz+RrHL0q8v816yWUkUJnuXNyTzx8h8WF50Ztmj2EdJj28vvOqZ1ws9t8O2nS0z4JVqEETfRfMeTHL+q9ql8DkDcCzM4OXBMQVrpmE/fHso2IhKCi6rYMFgvVbARuzp1QXmGA/dD3GJVg73Jj2e/Fy20PCLEZwc99EdZS8NaJnmcfbFB8WwnXVSGCYpRcQBijRUF9774Hi9WsSW0pPR//iwX7HvHAARYD3RnKRulS0k5g/yxN3zPLwz2hbzvqyy3UXAfIYq3bpX4s2Hkm4Y8fpbje9VRM/Nii/SWnyfc6oHBY1waq6IjI+EpxphlVLqyOkp7eZPWfMnwwwkwO22M9v5/5eqyMuRCyavTJtLrmIG5zKi45MaVbDS952zToexgegvUBO6OPRzlfmWUg/N4mMYR2hcfVIb4NJPGezhSDSwm/vDUVgMxGpCFBybJmhWoCiRpc1iAhs3teTWHJBLFaByMYVmM+kQ6f5pP8QadWAsfbmaPd3H2/qGN0G5RXfPChBT6k6o=
