version: '3.7'
services:
    web:
         build: nginx/
         volumes:
             - ./nginx:/usr/share/nginx/html/
             - ./nginx:/etc/nginx/certs/
         ports:
             - "8080:80"
             - "443:443"
    app:
        container_name: dockerized-react-app
        build: 
            context: .
            #dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        #ports: 
        #    - 3000:3000
        environment:
            - NODE_ENV=development
