FROM nginx:latest
#COPY index.html /usr/share/nginx/html/index.html
COPY default.conf /etc/nginx/conf.d/

#criando um container nginx e copiando o que tem no default para ele, para o redirecionamento
